name: Build site and deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.8.4'
      CABAL_VERSION: '3.0.0.0'
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2.3.4
      - name: Setup environment
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          cabal-version: ${{ env.CABAL_VERSION }}


      - run: cabal new-update
      - run: cabal new-build --only-dependencies
        # - run: cabal new-freeze

        # - name: Cache cabal deps
        #   uses: actions/cache@v2
        #   with:
        #     path: |
        #       ~/.cabal/store
        #       dist-newstyle
        #     key: ${{ runner.os }}-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
        #     restore-keys: |
        #       ${{ runner.os }}-${{ env.GHC_VERSION }}-

      - name: Run site build
        run: cabal new-run site build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: _site
